### ISSUE TITLE
split_value.md パターン追加　便潜血

### ISSUE THREAD

**Issue by imoan1983** [nhoHQ/SSMIX2_support_documents#105]
|ヘモグロビン・トランスフェリン[便] 検体識別-  2|1B042130201519011|Hb(記号1)Tf(記号2)|Hb+Tr-|1B042130201519051|1B042130201519052|記号1|記号2||
|ヘモグロビン・トランスフェリン[便] 検体識別-  3|1B042130301519011|Hb(記号1)Tf(記号2)|Hb+Tr-|1B042130301519051|1B042130301519052|記号1|記号2||

**Comment by ktktkt** [comment]
訂正
|ヘモグロビン・トランスフェリン[便] 検体識別- 2|1B042130201519011|Hb(記号1)Tf(記号2)|Hb+Tf-|1B042130201519051|1B042130201519052|記号1|記号2||
|ヘモグロビン・トランスフェリン[便] 検体識別- 3|1B042130301519011|Hb(記号1)Tf(記号2)|Hb+Tf-|1B042130301519051|1B042130301519052|記号1|記号2||
