### ISSUE TITLE
split_value.md 追記

### ISSUE THREAD

**Issue by imoan1983** [nhoHQ/SSMIX2_support_documents#240]
`クロストリディウムディフィシル抗原 5E110000001519011 Ag(記号)/Tox(記号)　Ag＋/Tox-　5E110000001519051　5E110000001519052　記号　記号`

**Comment by ktktkt** [comment]
`|クロストリディウムディフィシル抗原|5E110000001519011|Ag(記号1)/Tox(記号2)|Ag＋/Tox-|5E110000001519051|5E110000001519052|記号1|記号2||`
